"""Fresh observations reach the configured model while a goal is running, and
the request lifecycle never stalls the local loop.

This file carries three things:

* the P03 admission-seam fixture double (with the frozen refusal tokens and a
  call audit), shared with ``test_goal_revision_and_cancel``;
* the builder for ``tests/fixtures/pilot/delayed-replies`` — the episode is
  generated by driving the real broker, the shared scripted transport and the
  real Recorder, so the fixture's provenance is the pilot's own recorded
  output (slice: authored and generated through the real recorder; no
  provider cost);
* the acceptance tests for observation updates, evidence selection, the
  anticipatory rule and the observation-freshness bound.

Expectations below are hand-written from the slice's anomaly matrix, not
generated from the builder's output.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


from embodied.bench.recorder import Recorder, RunManifest, replay
from embodied.cli import CommandStatus
from embodied.contracts.records import (
    ClockStamp,
    DecisionRequest,
    ExecutionDisposition,
    ExecutionStatus,
    FrameQuality,
    GoalDisposition,
    GoalStatus,
    MissionContract,
    Observation,
    SelectionGeometry,
    SensorIds,
    SensorMode,
    SpatialGoal,
    VisualSelection,
    to_dict,
)

from embodied.pilot.broker import AdmissionContext, PilotBroker
from embodied.pilot.decisions import DecisionEngine, PilotParameters, SceneStatus
from embodied.pilot.provider import (
    ModelConfig,
    Provider,
    RequestPacket,
    ScriptedReply,
    ScriptedTransport,
)
from embodied.pilot.tools import TOOL_SCHEMAS

FIXTURES = Path(__file__).resolve().parents[1] / "fixtures" / "pilot"
EPISODE = FIXTURES / "delayed-replies"
REPO = Path(__file__).resolve().parents[2]
RUNTIME_MODEL_CONFIG = REPO / "configs" / "runtime-model.yaml"

HOST, CLOCK = "pilot-fixture-0", "monotonic"
MODEL_IDENTITY = "opencode-go/deepseek-v4.1-flash"


def S(seconds: float) -> ClockStamp:
    return ClockStamp(HOST, CLOCK, round(seconds * 1_000_000_000))


def parameters(**overrides) -> PilotParameters:
    values = dict(
        event_deadband=0.08,
        max_silence_s=6.0,
        latency_budget_s=2.5,
        guard_margin_s=1.0,
        response_deadline_s=4.0,
        observation_freshness_s=6.0,
        retry_budget=1,
    )
    values.update(overrides)
    return PilotParameters(**values)


# ---------------------------------------------------------------------------
# The P03 admission seam, doubled. P03's executor replaces this at P05.
# ---------------------------------------------------------------------------


class SeamFixture:
    """Final goal admission as a test double, with the frozen refusal tokens
    from the P03 plan and an audit of every call."""

    REFUSAL_TOKENS = (
        "stale_pose",
        "missing_depth",
        "frame_epoch_mismatch",
        "calibration_mismatch",
        "detector_unavailable",
        "unknown_geometry",
    )

    def __init__(self, refuse_with: str | None = None) -> None:
        self.refuse_with = refuse_with
        self.admit_calls: list[SpatialGoal] = []
        self.cancel_calls: list[tuple[str, int, str]] = []
        self.invalidations: dict[str, int] = {}
        self.queued_samples = 2
        self._counter = 0

    def admit(self, proposal: SpatialGoal, context: AdmissionContext) -> GoalStatus:
        self.admit_calls.append(proposal)
        if self.refuse_with is not None:
            return GoalStatus(
                proposal_id=proposal.proposal_id,
                request_id=proposal.request_id or "local",
                disposition=GoalDisposition.REJECTED,
                reason=self.refuse_with,
                admission_ref=None,
                current_disposition=ExecutionDisposition.NOT_STARTED,
            )
        self._counter += 1
        return GoalStatus(
            proposal_id=proposal.proposal_id,
            request_id=proposal.request_id or "local",
            disposition=GoalDisposition.ACCEPTED,
            reason=None,
            admission_ref=f"g{self._counter}",
            current_disposition=ExecutionDisposition.RUNNING,
        )

    def cancel(self, goal_id: str, expected_revision: int, idempotency_key: str) -> GoalStatus:
        self.cancel_calls.append((goal_id, expected_revision, idempotency_key))
        return GoalStatus(
            proposal_id=idempotency_key,
            request_id=f"cancel-{idempotency_key}",
            disposition=GoalDisposition.CANCELLED,
            reason=None,
            admission_ref=goal_id,
            current_disposition=ExecutionDisposition.CANCELLED,
        )

    def status(self, goal_id: str) -> ExecutionStatus:
        return ExecutionStatus(
            goal_ref=goal_id,
            certificate_ref=None,
            command_ref=None,
            disposition=ExecutionDisposition.RUNNING,
            evidence=(),
            reasons=(),
            horizon_s=None,
            capabilities=(),
        )

    def invalidate_queued(self, goal_id: str) -> int:
        self.invalidations[goal_id] = self.invalidations.get(goal_id, 0) + self.queued_samples
        return self.invalidations[goal_id]


# ---------------------------------------------------------------------------
# Record builders
# ---------------------------------------------------------------------------


def make_observation(
    record_id: str,
    sequence: int,
    capture_ns: int,
    receipt_ns: int,
    episode_id: str = "delayed-replies-001",
    left_payload: str | None = None,
) -> Observation:
    return Observation(
        episode_id=episode_id,
        record_id=record_id,
        sensor_ids=SensorIds(left="pilot-left", right="pilot-right", imu="pilot-imu"),
        sequence=sequence,
        capture_stamp=ClockStamp(HOST, CLOCK, capture_ns),
        receipt_stamp=ClockStamp(HOST, CLOCK, receipt_ns),
        sim_time_s=None,
        pair_id=f"pair-{record_id}" if left_payload else None,
        left_payload=left_payload,
        right_payload=left_payload.replace("left", "right") if left_payload else None,
        encoding="ppm-p3",
        width=16,
        height=12,
        calibration_id="cal-pilot-0",
        capture_pose_ref=None,
        quality=FrameQuality(
            is_colour=True,
            channel_identical_fraction=0.0,
            channel_means=(0.35, 0.28, 0.4),
            saturated_pixel_fraction=0.0,
        ),
        depth_source=None,
    )


def make_selection(selection_id: str, observation_id: str) -> VisualSelection:
    return VisualSelection(
        selection_id=selection_id,
        observation_id=observation_id,
        coordinate_convention="pixel_xy",
        geometry_kind=SelectionGeometry.POINT,
        geometry=(10.0, 5.0),
        crop_transform=None,
        description="red object candidate",
        confidence=0.6,
    )


def make_proposal(
    proposal_id: str,
    request_id: str,
    fingerprint: str,
    base_goal_revision: int,
    selection_ids: tuple[str, ...] = (),
    intent: str = "inspect",
    lease_s: float = 20.0,
) -> SpatialGoal:
    return SpatialGoal(
        proposal_id=proposal_id,
        request_id=request_id,
        fingerprint=fingerprint,
        mission_revision=0,
        base_goal_revision=base_goal_revision,
        selection_ids=selection_ids,
        target_refs=(),
        intent=intent,
        constraints=("indoor_only",),
        completion_condition="candidate inspected from a reachable view",
        lease_bounds=(("total_s", lease_s),),
        local_discretion_bounds=(("radius_m", 3.0),),
    )


def make_request(
    request_id: str,
    sequence: int,
    base_goal_revision: int,
    observation_ids: tuple[str, ...],
) -> DecisionRequest:
    return DecisionRequest(
        request_id=request_id,
        sequence=sequence,
        mission_revision=0,
        base_goal_revision=base_goal_revision,
        observation_ids=observation_ids,
        snapshot_id=None,
        response_deadline_s=4.0,
        model_identity=MODEL_IDENTITY,
    )


def reply_document(proposals: tuple[SpatialGoal, ...]) -> dict:
    content = json.dumps({"spatial_goals": [to_dict(proposal) for proposal in proposals]})
    return {"choices": [{"message": {"content": content}}]}


def mission_contract() -> MissionContract:
    return MissionContract(
        mission_id="mission-delayed-replies",
        instruction="Find the red object, inspect it, and return to the start.",
        interpreted_requirements=("find_red_object", "inspect_red_object", "return_to_start"),
        revision=0,
        evidence_obligations=("cite_observations_for_each_claim",),
        return_obligation="return_to_start",
        allowed_scope="lab_rooms",
        budget=(("mission_time_s", 30.0),),
        unresolved_questions=(),
    )


# ---------------------------------------------------------------------------
# The delayed-replies episode builder
# ---------------------------------------------------------------------------

# Scenario, all stamps in seconds (one clock domain; the recorder enforces
# non-decreasing order at write time):
#
#   1.00  mission recorded
#   1.05  obs-0 captured 1.00 — fresh; G1 (P1) admitted on sel-0
#   1.50  execution g1 running
#   2.00  req-1 sent (deadline 6.0)
#   2.45  obs-1 captured 2.40 — fresh, new target visible
#   2.50  req-2 sent, urgent: req-1 marked obsolete
#   3.00  req-2's reply: P2 admitted (g2 supersedes g1, queued invalidated);
#         the reply carried P2 twice — the repeat is idempotent, no second
#         admission
#   3.50  req-3 sent; 4.00 its reply proposes P2's id under a different
#         fingerprint — conflict, rejected
#   4.60  req-1's late reply (P1b) lands after req-2 superseded it —
#         reordered: recorded with the dead request named, not applied
#   5.00  req-4 sent (deadline 9.0)
#   8.00  obs-2 captured 0.20 but delivered 7.8s late — stale at arrival,
#         recorded with its age, never treated as current
#   9.40  req-4's reply lands 4.4s after send — delayed: expired, the delay is
#         recorded and never zeroed
#   9.60  req-5 sent; 10.00 its reply proposes P5 grounded on stale obs-2 —
#         rejected: a fresh goal is not grounded on stale evidence
#  12.00  req-6 sent, no scripted reply — silence
#  16.20  req-6 expires at tick; g2 continues within lease, reason recorded
#  16.40  cancel g2 with wrong expected revision — rejected
#  16.60  cancel g2 at its revision — cancelled, only g2
#  16.80  the same cancel key repeated — idempotent, same disposition


def build_delayed_replies_episode(episode_dir: Path) -> dict:
    """Drive the real broker, the shared scripted transport and the real
    Recorder through the scenario. Returns the closed manifest."""
    recorder = Recorder(episode_dir)
    log: list[tuple[str, dict, ClockStamp]] = []

    def sink(kind, payload, stamp, sim_time_s=None):
        log.append((kind, payload, stamp))

    seam = SeamFixture()
    transport = ScriptedTransport()
    provider = Provider(
        ModelConfig(
            provider="opencode-go",
            id=MODEL_IDENTITY,
            base_url="https://opencode.ai/zen/go/v1",
            api="openai-completions",
            image_transport="base64",
        ),
        transport,
        TOOL_SCHEMAS,
    )
    broker = PilotBroker(seam, parameters(), provider, host_id=HOST, clock_id=CLOCK, sink=sink)

    def ppm(marker_shift: int) -> bytes:
        rows = []
        for y in range(12):
            row = []
            for x in range(16):
                if marker_shift <= x <= marker_shift + 2 and 4 <= y <= 6:
                    row.append("220 30 30")
                else:
                    row.append(f"{40 + 6 * x} {60 + 4 * y} 90")
            rows.append("\n".join(row))
        return "P3\n16 12\n255\n".encode() + ("\n".join(rows) + "\n").encode()

    payloads = {
        "obs-0-left.ppm": ppm(10),
        "obs-0-right.ppm": ppm(8),
        "obs-1-left.ppm": ppm(4),
        "obs-1-right.ppm": ppm(2),
        "obs-2-left.ppm": ppm(10),
        "obs-2-right.ppm": ppm(8),
    }
    for name, data in payloads.items():
        recorder.write_payload(name, data)

    def harness(kind: str, payload, stamp: ClockStamp) -> None:
        log.append((kind, to_dict(payload), stamp))

    def drain() -> None:
        while log:
            kind, payload, stamp = log.pop(0)
            recorder.record(kind, payload, stamp)

    transport.schedule(
        ScriptedReply(delay_s=2.6, document=reply_document(
            (make_proposal("P1b", "req-1", "fp-P1b", 1, ("sel-0",), "explore"),))),
        ScriptedReply(delay_s=0.5, document=reply_document(
            (make_proposal("P2", "req-2", "fp-P2", 1, ("sel-1",)),
             make_proposal("P2", "req-2", "fp-P2", 1, ("sel-1",))))),
        ScriptedReply(delay_s=0.5, document=reply_document(
            (make_proposal("P2", "req-3", "fp-P2-conflict", 2, ("sel-1",)),))),
        ScriptedReply(delay_s=4.4, document=reply_document(
            (make_proposal("P4", "req-4", "fp-P4", 2, ("sel-1",), "explore"),))),
        ScriptedReply(delay_s=0.4, document=reply_document(
            (make_proposal("P5", "req-5", "fp-P5", 2, ("sel-2",)),))),
    )

    broker.set_mission(mission_contract(), S(1.00))
    drain()

    obs0 = make_observation("obs-0", 0, 1_000_000_000, 1_050_000_000, left_payload="obs-0-left.ppm")
    harness("observation", obs0, S(1.05))
    assert broker.on_observation(obs0, S(1.05)).fresh
    sel0 = make_selection("sel-0", "obs-0")
    harness("selection", sel0, S(1.10))
    broker.register_selection(sel0)
    broker.set_goal(make_proposal("P1", "local-initial", "fp-P1", 0, ("sel-0",), "explore"), S(1.20))
    drain()
    harness("execution", _execution("g1", "running"), S(1.50))
    drain()

    def packet(request: DecisionRequest) -> RequestPacket:
        return RequestPacket(
            request=request,
            mission_instruction=mission_contract().instruction,
            target_refs=(),
        )

    broker.submit(make_request("req-1", 0, 1, ("obs-0",)), packet(make_request("req-1", 0, 1, ("obs-0",))), S(2.00))
    drain()

    obs1 = make_observation("obs-1", 1, 2_400_000_000, 2_450_000_000, left_payload="obs-1-left.ppm")
    harness("observation", obs1, S(2.45))
    assert broker.on_observation(obs1, S(2.45)).fresh
    sel1 = make_selection("sel-1", "obs-1")
    harness("selection", sel1, S(2.48))
    broker.register_selection(sel1)
    request2 = make_request("req-2", 1, 1, ("obs-1",))
    broker.submit(request2, packet(request2), S(2.50), supersede_outstanding=True)
    drain()

    broker.poll(S(3.00))
    drain()
    harness("execution", _execution("g2", "running"), S(3.20))
    drain()

    request3 = make_request("req-3", 2, 2, ("obs-1",))
    broker.submit(request3, packet(request3), S(3.50))
    drain()
    broker.poll(S(4.00))
    drain()
    harness("execution", _execution("g2", "running"), S(4.20))
    drain()

    broker.poll(S(4.60))
    drain()
    harness("execution", _execution("g2", "running"), S(4.80))
    drain()

    request4 = make_request("req-4", 3, 2, ("obs-1",))
    broker.submit(request4, packet(request4), S(5.00))
    drain()

    obs2 = make_observation("obs-2", 2, 200_000_000, 8_000_000_000, left_payload="obs-2-left.ppm")
    harness("observation", obs2, S(8.00))
    stale_age = broker.on_observation(obs2, S(8.00))
    assert not stale_age.fresh and stale_age.age_s > 6.0
    sel2 = make_selection("sel-2", "obs-2")
    harness("selection", sel2, S(8.10))
    broker.register_selection(sel2)
    harness("execution", _execution("g2", "running"), S(8.20))
    drain()

    broker.poll(S(9.40))
    drain()
    request5 = make_request("req-5", 4, 2, ("obs-1",))
    broker.submit(request5, packet(request5), S(9.60))
    drain()
    broker.poll(S(10.00))
    drain()

    request6 = make_request("req-6", 5, 2, ("obs-1",))
    broker.submit(request6, packet(request6), S(12.00))
    drain()

    broker.tick(S(16.20))
    drain()
    broker.cancel("g2", 99, "cancel-wrong-1", S(16.40))
    drain()
    broker.cancel("g2", 2, "cancel-right-1", S(16.60))
    drain()
    broker.cancel("g2", 2, "cancel-right-1", S(16.80))
    drain()

    manifest = recorder.close(
        RunManifest(
            episode_id="delayed-replies-001",
            episode_kind="synthetic-fixture",
            arm="B2",
            sensor_mode=SensorMode.SIMULATOR_INTERFACE,
            model_identity=f"{MODEL_IDENTITY} (scripted replies; no live provider call)",
        )
    )
    return manifest_to_dict(manifest)


def _execution(goal_ref: str, disposition_value: str) -> ExecutionStatus:
    return ExecutionStatus(
        goal_ref=goal_ref,
        certificate_ref=None,
        command_ref=None,
        disposition=ExecutionDisposition(disposition_value),
        evidence=(),
        reasons=(),
        horizon_s=None,
        capabilities=(),
    )


def manifest_to_dict(manifest: RunManifest) -> dict:
    from embodied.bench.recorder import manifest_to_dict as to_mapping

    return to_mapping(manifest)


# ---------------------------------------------------------------------------
# Tests: fresh observations reach the configured model (slice line 9)
# ---------------------------------------------------------------------------


def _fresh_observation_at(record_id: str, capture_s: float, now_s: float) -> Observation:
    return make_observation(record_id, 0, int(capture_s * 1e9), int(now_s * 1e9))


def test_fresh_observation_mid_goal_reaches_the_configured_model():
    seam = SeamFixture()
    broker = PilotBroker(seam, parameters(), host_id=HOST, clock_id=CLOCK)
    broker.set_mission(mission_contract(), S(1.0))
    broker.set_goal(
        make_proposal("P0", "local", "fp-P0", 0, ("sel-x",), "explore"), S(1.2)
    )
    observation = _fresh_observation_at("obs-mid", 5.0, 5.1)
    broker.on_observation(observation, S(5.1))
    engine = DecisionEngine(parameters(), MODEL_IDENTITY)
    decision = engine.consider(
        S(5.2),
        SceneStatus(signature=0.9, new_targets=("red-object",)),
        broker.observations,
        0,
        broker.base_goal_revision,
        broker.outstanding_request,
    )
    assert decision.send and "new_target" in decision.reason
    assert decision.request is not None
    assert "obs-mid" in decision.request.observation_ids
    assert decision.request.model_identity == MODEL_IDENTITY
    config_text = RUNTIME_MODEL_CONFIG.read_text(encoding="utf-8")
    assert "opencode-go/deepseek-v4.1-flash" in config_text


# ---------------------------------------------------------------------------
# Tests: local operation does not wait on inference (§15.3)
# ---------------------------------------------------------------------------


def test_local_loop_continues_while_a_request_is_outstanding():
    seam = SeamFixture()
    transport = ScriptedTransport()  # schedules nothing: silence
    provider = Provider(
        ModelConfig("opencode-go", MODEL_IDENTITY, "https://x", "openai-completions", "base64"),
        transport,
        TOOL_SCHEMAS,
    )
    broker = PilotBroker(seam, parameters(), provider, host_id=HOST, clock_id=CLOCK)
    broker.set_mission(mission_contract(), S(1.0))
    request = make_request("req-silent", 0, 0, ())
    broker.submit(
        request,
        RequestPacket(request=request, mission_instruction="m"),
        S(2.0),
    )
    execution_stamps = []
    for step in range(3):
        now = S(2.5 + step)
        observation = _fresh_observation_at(f"obs-{step}", 2.4 + step * 0.1, 2.5 + step)
        broker.on_observation(observation, now)
        broker.tick(now)
        assert broker.poll(now) == ()
        execution_stamps.append(now)
    # The whole loop ran in logical time while the request stayed outstanding.
    assert broker.outstanding_request is not None
    assert broker.outstanding_request.request_id == "req-silent"
    assert [stamp.monotonic_ns for stamp in execution_stamps] == [
        S(2.5).monotonic_ns,
        S(3.5).monotonic_ns,
        S(4.5).monotonic_ns,
    ]


# ---------------------------------------------------------------------------
# Tests: evidence selection triggers, deadband, silence, dedup (§9.1–9.2)
# ---------------------------------------------------------------------------


def _engine_with_one_observation() -> tuple[DecisionEngine, dict]:
    observation = _fresh_observation_at("obs-a", 1.0, 1.1)
    return DecisionEngine(parameters(), MODEL_IDENTITY), {"obs-a": observation}


def test_each_specified_trigger_fires():
    cases = [
        (SceneStatus(signature=0.5, explicit_question="which branch?"), "explicit_question"),
        (SceneStatus(signature=0.5, map_conflict=True), "map_conflict"),
        (SceneStatus(signature=0.5, lost_targets=("t1",)), "lost_target"),
        (SceneStatus(signature=0.5, new_targets=("t2",)), "new_target"),
        (SceneStatus(signature=0.5, identity_ambiguity=True), "identity_ambiguity"),
        (SceneStatus(signature=0.5, horizon_s=1.0), "reduced_horizon"),
        (SceneStatus(signature=0.95), "signature_change"),
    ]
    for scene, expected in cases:
        engine, observations = _engine_with_one_observation()
        # One prior send establishes the deadband/silence/horizon history the
        # later rules compare against.
        primed = engine.consider(S(1.2), SceneStatus(signature=0.5, horizon_s=10.0), observations, 0, 0, None)
        assert primed.send
        decision = engine.consider(S(2.0), scene, observations, 0, 0, None)
        assert decision.send, f"{expected} did not fire"
        assert expected in decision.reason, f"{decision.reason} does not name {expected}"


def test_the_first_scene_is_sent_because_nothing_has_been_reviewed_yet():
    engine, observations = _engine_with_one_observation()
    decision = engine.consider(S(1.2), SceneStatus(signature=0.5), observations, 0, 0, None)
    assert decision.send and decision.reason == "initial_scene"


def test_deadband_suppresses_insignificant_repeats():
    engine, observations = _engine_with_one_observation()
    first = engine.consider(S(2.0), SceneStatus(signature=0.5), observations, 0, 0, None)
    assert first.send and first.reason == "initial_scene"
    tiny = engine.consider(S(2.5), SceneStatus(signature=0.53), observations, 0, 0, None)
    assert not tiny.send and tiny.reason == "no_trigger"
    significant = engine.consider(S(2.6), SceneStatus(signature=0.75), observations, 0, 0, None)
    assert significant.send and significant.reason == "signature_change"


def test_max_silence_forces_a_review_of_a_static_scene():
    engine, observations = _engine_with_one_observation()
    first = engine.consider(S(1.0), SceneStatus(signature=0.5), observations, 0, 0, None)
    assert first.send
    quiet = engine.consider(S(5.0), SceneStatus(signature=0.5), observations, 0, 0, None)
    assert not quiet.send
    forced = engine.consider(S(8.0), SceneStatus(signature=0.5), observations, 0, 0, None)
    assert forced.send and forced.reason == "max_silence"


def test_dedup_prevents_a_second_identical_request_within_the_freshness_window():
    engine, observations = _engine_with_one_observation()
    first = engine.consider(S(1.0), SceneStatus(signature=0.9, new_targets=("t",)), observations, 0, 0, None)
    assert first.send and first.reason == "new_target"
    second = engine.consider(S(1.5), SceneStatus(signature=0.9, new_targets=("t",)), observations, 0, 0, None)
    assert not second.send and second.reason == "deduplicated"
    # A different evidence requirement about the same subject is not a duplicate.
    third = engine.consider(S(1.6), SceneStatus(signature=0.9, lost_targets=("t",)), observations, 0, 0, None)
    assert third.send and third.reason == "lost_target"


# ---------------------------------------------------------------------------
# Tests: anticipatory rule (§9.3, §17.3)
# ---------------------------------------------------------------------------


def test_anticipatory_send_fires_as_the_boundary_approaches_and_supersedes():
    engine, observations = _engine_with_one_observation()
    primed = engine.consider(S(0.5), SceneStatus(signature=0.5, decision_boundary_s=30.0), observations, 0, 0, None)
    assert primed.send and primed.reason == "initial_scene"
    early = engine.consider(S(1.0), SceneStatus(signature=0.5, decision_boundary_s=30.0), observations, 0, 0, None)
    assert not early.send
    approaching = engine.consider(
        S(1.5), SceneStatus(signature=0.5, decision_boundary_s=3.0), observations, 0, 0, None
    )
    assert approaching.send and approaching.reason == "decision_boundary_approaching"
    assert approaching.supersede_outstanding is False  # nothing outstanding to supersede
    outstanding = make_request("req-live", 0, 0, ())
    urgent = engine.consider(
        S(2.0),
        SceneStatus(signature=0.5, decision_boundary_s=2.0),
        observations,
        0,
        0,
        outstanding,
    )
    assert urgent.send and urgent.supersede_outstanding


# ---------------------------------------------------------------------------
# Tests: observe never moves the aircraft (§9.2)
# ---------------------------------------------------------------------------


def test_observe_returns_unmet_with_objectives_and_admits_nothing():
    from embodied.pilot.tools import ToolSurface

    seam = SeamFixture()
    broker = PilotBroker(seam, parameters(), host_id=HOST, clock_id=CLOCK)
    surface = ToolSurface(broker, now=lambda: S(2.0))
    outcome = surface.observe("behind the door", max_age_s=2.0, requires_movement=True)
    assert outcome.state == "unmet"
    assert outcome.proposed_objectives
    assert "does not move the aircraft" in outcome.unmet_requirement
    assert seam.admit_calls == []


def test_observe_returns_existing_evidence_without_a_new_capture():
    from embodied.pilot.tools import ToolSurface

    seam = SeamFixture()
    broker = PilotBroker(seam, parameters(), host_id=HOST, clock_id=CLOCK)
    observation = _fresh_observation_at("obs-known", 1.0, 1.1)
    broker.on_observation(observation, S(1.1))
    surface = ToolSurface(broker, now=lambda: S(2.0))
    outcome = surface.observe("obs-known", max_age_s=6.0)
    assert outcome.state == "existing"
    assert outcome.observation_ids == ("obs-known",)
    assert seam.admit_calls == []


def test_observe_treats_a_requested_detail_as_a_real_requirement():
    from embodied.pilot.tools import ToolSurface

    seam = SeamFixture()
    broker = PilotBroker(seam, parameters(), host_id=HOST, clock_id=CLOCK)
    observation = _fresh_observation_at("obs-known", 1.0, 1.1)
    broker.on_observation(observation, S(1.1))
    surface = ToolSurface(broker, now=lambda: S(2.0))

    broad = surface.observe("obs-known", max_age_s=6.0, detail="any")
    assert broad.state == "existing"
    close_up = surface.observe("obs-known", max_age_s=6.0, detail="close-up")
    assert close_up.state == "pending"
    assert "close-up" in close_up.unmet_requirement
    assert seam.admit_calls == []


def test_observe_flags_stale_evidence_as_pending_not_current():
    from embodied.pilot.tools import ToolSurface

    seam = SeamFixture()
    broker = PilotBroker(seam, parameters(), host_id=HOST, clock_id=CLOCK)
    stale = make_observation("obs-old", 0, 100_000_000, 8_000_000_000)
    broker.on_observation(stale, S(8.0))
    surface = ToolSurface(broker, now=lambda: S(8.1))
    outcome = surface.observe("obs-old", max_age_s=6.0)
    assert outcome.state == "pending"
    assert "older than" in outcome.unmet_requirement


# ---------------------------------------------------------------------------
# Tests: the shared degradation path is one seam for every arm
# ---------------------------------------------------------------------------


def test_shared_transport_script_applies_identically_to_two_brokers():
    document = reply_document((make_proposal("PX", "req-r", "fp-PX", 0, ("sel-0",)),))

    def run_one() -> tuple[str, int]:
        seam = SeamFixture()
        transport = ScriptedTransport()
        transport.schedule(ScriptedReply(delay_s=1.5, document=document))
        provider = Provider(
            ModelConfig("opencode-go", MODEL_IDENTITY, "https://x", "openai-completions", "base64"),
            transport,
            TOOL_SCHEMAS,
        )
        broker = PilotBroker(seam, parameters(), provider, host_id=HOST, clock_id=CLOCK)
        observation = _fresh_observation_at("obs-shared", 1.0, 1.1)
        broker.on_observation(observation, S(1.1))
        selection = make_selection("sel-0", "obs-shared")
        broker.register_selection(selection)
        request = make_request("req-r", 0, 0, ("obs-shared",))
        broker.submit(request, RequestPacket(request=request, mission_instruction="m"), S(2.0))
        broker.poll(S(3.6))
        broker.poll(S(3.7))
        status = next(
            outcome.status for outcome in reversed(broker.outcomes) if outcome.status is not None
        )
        return (status.disposition.value, transport.sent_stamps[0].monotonic_ns)

    assert run_one() == run_one()


def test_shared_freshness_bound_rejects_stale_grounding_regardless_of_arm():
    for provider_or_none in (None, "with-provider"):
        seam = SeamFixture()
        provider = None
        if provider_or_none == "with-provider":
            provider = Provider(
                ModelConfig("opencode-go", MODEL_IDENTITY, "https://x", "openai-completions", "base64"),
                ScriptedTransport(),
                TOOL_SCHEMAS,
            )
        broker = PilotBroker(seam, parameters(), provider, host_id=HOST, clock_id=CLOCK)
        stale = make_observation("obs-stale", 0, 100_000_000, 8_000_000_000)
        broker.on_observation(stale, S(8.0))
        selection = make_selection("sel-stale", "obs-stale")
        broker.register_selection(selection)
        outcome = broker.set_goal(
            make_proposal("PS", "local", "fp-PS", 0, ("sel-stale",)), S(8.2)
        )
        assert outcome.status.disposition is GoalDisposition.REJECTED
        assert "stale_observation" in outcome.status.reason
        assert "obs-stale" in outcome.status.reason
        assert "age_s=8.100" in outcome.status.reason
        assert seam.admit_calls == []


# ---------------------------------------------------------------------------
# Tests: the checked-in delayed-replies episode
# ---------------------------------------------------------------------------


def _artifact_hashes(episode_dir: Path) -> dict:
    manifest = json.loads((episode_dir / "manifest.json").read_text(encoding="utf-8"))
    return manifest["artifacts"]


def test_checked_in_episode_replays_in_recorded_order(tmp_path):
    document = replay(EPISODE)
    kinds = [entry["kind"] for entry in document["timeline"]]
    assert document["episode_id"] == "delayed-replies-001"
    assert document["sensor_mode"] == "simulator-interface"
    assert document["report"] is None
    counts = document["counts"]
    assert counts == {
        "execution": 6,
        "goal": 5,
        "goal_status": 11,
        "mission": 1,
        "observation": 3,
        "request": 6,
        "selection": 3,
    }
    # Order at the scenario's heart: the revision lands while g1 runs, and the
    # loop keeps recording execution throughout.
    assert kinds[:2] == ["mission", "observation"]
    assert kinds[3:5] == ["goal", "goal_status"]
    revision_at = kinds.index("goal_status", kinds.index("request"))  # P2's accepted status
    assert "execution" in kinds[revision_at:], "no local execution follows the revision"
    assert "obs-2" in [
        entry["summary"].get("record_id")
        for entry in document["timeline"]
        if entry["kind"] == "observation"
    ]


def test_goal_statuses_in_the_episode_carry_every_recorded_anomaly():
    document = replay(EPISODE)
    statuses = [entry["summary"] for entry in document["timeline"] if entry["kind"] == "goal_status"]
    dispositions = [status["disposition"] for status in statuses]
    assert dispositions.count("accepted") == 3          # P1, P2, and P2's idempotent repeat
    assert dispositions.count("superseded") == 2        # g1 by P2, late P1b on dead req-1
    assert dispositions.count("rejected") == 3          # conflict, stale observation, wrong-revision cancel
    assert dispositions.count("expired") == 1           # delayed P4
    assert dispositions.count("cancelled") == 2         # cancel-right + its idempotent repeat
    # The stale-grounding rejection records the measured age, not a bare no.
    events = AgentSurfaceEvents(EPISODE)
    stale = [
        payload
        for payload in events
        if payload["kind"] == "goal_status" and "stale_observation" in (payload["payload"].get("reason") or "")
    ]
    assert len(stale) == 1
    assert "age_s=9.800" in stale[0]["payload"]["reason"]
    assert "6.0" in stale[0]["payload"]["reason"]
    # The cloud-loss continuation names its cause on the running goal.
    executions = [
        payload
        for payload in events
        if payload["kind"] == "execution" and payload["payload"]["reasons"]
    ]
    assert any("req-6 expired" in reason for payload in executions for reason in payload["payload"]["reasons"])
    assert any("continuing within lease" in reason for payload in executions for reason in payload["payload"]["reasons"])


def AgentSurfaceEvents(episode_dir: Path) -> list[dict]:
    lines = (episode_dir / "agent-events.jsonl").read_text(encoding="utf-8").splitlines()
    return [json.loads(line) for line in lines if line.strip()]


def test_episode_regenerates_byte_identical(tmp_path):
    manifest = build_delayed_replies_episode(tmp_path / "regenerated")
    checked_in = _artifact_hashes(EPISODE)
    assert manifest["artifacts"] == checked_in


def test_bench_replay_command_accepts_the_checked_in_episode(tmp_path):
    from embodied.cli import main

    output = tmp_path / "run"
    code = main(["bench", "replay", "--episode", str(EPISODE), "--output", str(output)])
    assert code == 0
    receipt = json.loads((output / "receipt.json").read_text(encoding="utf-8"))
    assert receipt["status"] == "complete"
    assert receipt["gate_status"] == "pass"
    assert receipt["episode_id"] == "delayed-replies-001"

# ---------------------------------------------------------------------------
# Tests: the pilot-probe refuses a live call without a recorded budget, and
# never logs credentials (CLI-PLAN:12; slice line 13). Unit tests default to
# the deterministic fake transport and never perform a live call.
# ---------------------------------------------------------------------------


def _probe_config(tmp_path: Path, max_calls=None, spend_ceiling_usd=None) -> Path:
    import textwrap

    path = tmp_path / "runtime-model.yaml"
    path.write_text(
        textwrap.dedent(
            f"""
            model:
              provider: opencode-go
              id: {MODEL_IDENTITY}
              base_url: https://opencode.ai/zen/go/v1
              api: openai-completions
              image_transport: base64
              declared_input: [text, image]
            probe:
              max_calls: {max_calls if max_calls is not None else ''}
              spend_ceiling_usd: {spend_ceiling_usd if spend_ceiling_usd is not None else ''}
            pilot:
              event_deadband: 0.08
              max_silence_s: 6.0
              latency_budget_s: 2.5
              guard_margin_s: 1.0
              response_deadline_s: 4.0
              observation_freshness_s: 6.0
              retry_budget: 1
            """
        ).strip()
        + "\n",
        encoding="utf-8",
    )
    return path


def _probe_args(tmp_path: Path, config: Path, max_calls: int | None) -> argparse.Namespace:
    return argparse.Namespace(
        config=config,
        observation=FIXTURES / "observation.json",
        max_calls=max_calls,
        api_key_env="P04_PROBE_TEST_KEY",
        output=str(tmp_path / "out"),
    )


def test_pilot_probe_refuses_without_a_recorded_budget(tmp_path):
    import embodied.pilot.probe as probe

    config = _probe_config(tmp_path)  # limits absent, as shipped
    output = tmp_path / "out"
    output.mkdir()
    outcome = probe._handler(_probe_args(tmp_path, config, max_calls=3), output)
    assert outcome.status is CommandStatus.BLOCKED
    assert outcome.exit_code() == 2
    assert "refuses a live call without an explicit budget" in outcome.reasons[0]
    assert "no max_calls/spend_ceiling_usd recorded" in outcome.reasons[0]
    assert outcome.manifest["limits_recorded"] is False


def test_pilot_probe_refuses_without_an_explicit_max_calls_flag(tmp_path):
    import embodied.pilot.probe as probe

    config = _probe_config(tmp_path, max_calls=4, spend_ceiling_usd=1.0)
    outcome = probe._handler(_probe_args(tmp_path, config, max_calls=None), tmp_path / "out")
    assert outcome.status is CommandStatus.BLOCKED
    assert outcome.exit_code() == 2
    assert "no --max-calls" in outcome.reasons[0]


def test_pilot_probe_with_a_fake_transport_records_its_checks_and_no_credentials(tmp_path):
    import embodied.pilot.probe as probe

    config_path = _probe_config(tmp_path, max_calls=3, spend_ceiling_usd=1.0)
    config = probe.load_runtime_config(config_path)
    assert probe.probe_limits(config) == (3, 1.0)

    tool_call = {
        "type": "function",
        "function": {"name": "status", "arguments": '{"goal_id": "g1"}'},
    }
    transport = ScriptedTransport()
    transport.schedule(
        ScriptedReply(
            delay_s=0.4,
            document={"choices": [{"message": {"content": "the marker is red, upper right"}}]},
            usage={"total_tokens": 120},
        ),
        ScriptedReply(
            delay_s=0.3,
            document={"choices": [{"message": {"content": "ok", "tool_calls": [tool_call]}}]},
        ),
        ScriptedReply(
            delay_s=0.2,
            document={"choices": [{"message": {"content": "not json at all"}}]},
        ),
    )
    report = probe.execute_probe(config, FIXTURES / "observation.json", transport, max_calls=3)

    assert report.calls == 3
    assert report.image_ok and report.tools_ok
    checks = {check.name: check for check in report.checks}
    assert checks["image_support"].passed and "chars" in checks["image_support"].detail
    assert checks["tool_support"].passed and "status" in checks["tool_support"].detail
    assert checks["error_handling"].passed
    # Latency is recorded per call (including the malformed one), and the
    # round trip is labelled unseparated.
    assert len(report.latency) == 3
    assert all(record["round_trip_unseparated"] is True for record in report.latency)
    assert report.latency[0]["usage"] == {"total_tokens": 120}
    # The image really travelled: the transport saw a base64 data URI.
    first_document = transport.sent_documents[0]
    parts = first_document["messages"][0]["content"]
    assert any(
        part.get("image_url", {}).get("url", "").startswith("data:image/ppm;base64,")
        for part in parts
    )
    # No credential text is anywhere in the recorded output.
    rendered = json.dumps({"checks": [check.detail for check in report.checks], "latency": report.latency})
    assert "sk-" not in rendered and "Bearer" not in rendered
