"""Goal revision, cancellation, the reply-anomaly matrix and the three arms.

The expectations in this file are the slice's pass conditions written out by
hand: a cloud revision received during an active goal, correct supersession
and cancellation, continued local execution, timestamped delay accounting, the
full delayed/reordered/duplicated/conflicting/missing matrix each producing its
recorded disposition with no duplicate movement, and the three executives
compared under the same runner.

The anomaly cases are also present in the checked-in
``tests/fixtures/pilot/delayed-replies`` episode, which was generated by
driving the real broker and the real recorder; here the same rules are
exercised directly so a failure names the rule, not a fixture.
"""

from __future__ import annotations

import json
from pathlib import Path
import sys

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent))

from embodied.contracts.records import (
    ClaimKind,
    ClockStamp,
    ExecutionDisposition,
    GoalDisposition,
    Observation,
)

from embodied.pilot.broker import PilotBroker
from embodied.pilot.decisions import DecisionEngine
from embodied.pilot.executives import B0Conventional, B1OneShot, B2Continuous, OneShotBudgetSpent
from embodied.pilot.provider import (
    ModelConfig,
    Provider,
    RequestPacket,
    ScriptedReply,
    ScriptedTransport,
)
from embodied.pilot.recipe_runner import (
    Guard,
    MissionRecipe,
    RecipeRunner,
    RecipeStep,
    TargetSelector,
    assemble_claims,
    build_final_report,
)
from embodied.pilot.tools import TOOL_SCHEMAS

from test_live_observation_updates import (
    HOST,
    CLOCK,
    MODEL_IDENTITY,
    EPISODE,
    SeamFixture,
    S,
    make_observation,
    make_proposal,
    make_request,
    make_selection,
    mission_contract,
    parameters,
    reply_document,
)

FIXTURE_EPISODE = EPISODE


def _model_config() -> ModelConfig:
    return ModelConfig(
        provider="opencode-go",
        id=MODEL_IDENTITY,
        base_url="https://opencode.ai/zen/go/v1",
        api="openai-completions",
        image_transport="base64",
    )


def _broker(seam=None, provider=None, **overrides) -> tuple[PilotBroker, SeamFixture]:
    seam = seam or SeamFixture()
    return PilotBroker(
        seam, parameters(**overrides), provider, host_id=HOST, clock_id=CLOCK
    ), seam


def _event_payloads(episode_dir: Path) -> list[dict]:
    lines = (episode_dir / "agent-events.jsonl").read_text(encoding="utf-8").splitlines()
    return [json.loads(line) for line in lines if line.strip()]


# ---------------------------------------------------------------------------
# 1. A valid revision supersedes; an older reply cannot overwrite (§15.2)
# ---------------------------------------------------------------------------


def test_valid_revision_during_an_active_goal_supersedes_and_invalidates_queued_samples():
    transport = ScriptedTransport()
    transport.schedule(
        ScriptedReply(delay_s=0.5, document=reply_document(
            (make_proposal("P2", "req-1", "fp-P2", 1, ("sel-1",)),))),
    )
    broker, seam = _broker(provider=Provider(_model_config(), transport, TOOL_SCHEMAS))
    broker.set_mission(mission_contract(), S(1.0))
    broker.set_goal(make_proposal("P1", "local", "fp-P1", 0, ("sel-0",), "explore"), S(1.2))
    assert broker.active_goal_id == "g1" and broker.active_revision == 1

    observation = make_observation("obs-1", 1, 2_000_000_000, 2_050_000_000)
    broker.on_observation(observation, S(2.05))
    broker.register_selection(make_selection("sel-1", "obs-1"))
    request = make_request("req-1", 0, 1, ("obs-1",))
    broker.submit(request, RequestPacket(request=request, mission_instruction="m"), S(2.5))
    outcomes = broker.poll(S(3.0))

    assert broker.active_goal_id == "g2" and broker.active_revision == 2
    assert seam.invalidations["g1"] == seam.queued_samples  # invalidated atomically
    supersede = [
        outcome for outcome in outcomes
        if outcome.status is not None
        and outcome.status.disposition is GoalDisposition.SUPERSEDED
    ]
    assert supersede and "queued samples invalidated" in supersede[0].status.reason

    # The same revision, arriving again, is stale: an older reply cannot
    # overwrite the newer accepted goal.
    stale = broker.process_proposal(make_proposal("P3", "req-1", "fp-P3", 1, ("sel-1",)), S(4.0))
    assert stale.status.disposition is GoalDisposition.REJECTED
    assert "stale_revision" in stale.status.reason
    assert broker.active_revision == 2


# ---------------------------------------------------------------------------
# 2. The anomaly matrix (§15.2, §15.3, §17.3, §18)
# ---------------------------------------------------------------------------


def _anomaly_episode_payloads() -> list[dict]:
    return [entry["payload"] for entry in _event_payloads(FIXTURE_EPISODE)]


def test_delayed_reply_is_expired_with_its_delay_recorded_not_zeroed():
    payloads = _anomaly_episode_payloads()
    delayed = [
        payload for payload in payloads
        if payload.get("disposition") == "expired"
    ]
    assert len(delayed) == 1
    assert "delayed_reply: 4.400s exceeds response_deadline_s=4.0" in delayed[0]["reason"]


def test_reordered_reply_names_the_dead_request_and_is_not_applied():
    payloads = _anomaly_episode_payloads()
    reordered = [
        payload for payload in payloads
        if "reordered_reply" in (payload.get("reason") or "")
    ]
    assert len(reordered) == 1
    assert "req-1 is obsolete" in reordered[0]["reason"]
    assert reordered[0]["disposition"] == "superseded"


def test_duplicated_proposal_is_idempotent_with_no_second_admission():
    payloads = _anomaly_episode_payloads()
    duplicates = [
        payload for payload in payloads
        if "duplicate: idempotent repeat" in (payload.get("reason") or "")
    ]
    assert len(duplicates) == 1
    assert duplicates[0]["disposition"] == "accepted"
    # Two P2 proposals arrived; the seam was asked to admit one goal for them.
    goals = [payload for payload in payloads if payload.get("proposal_id") == "P2" and payload.get("intent")]
    assert len(goals) == 1


def test_conflicting_payload_under_a_used_proposal_id_is_rejected():
    payloads = _anomaly_episode_payloads()
    conflicts = [
        payload for payload in payloads
        if "proposal_conflict" in (payload.get("reason") or "")
    ]
    assert len(conflicts) == 1
    assert conflicts[0]["disposition"] == "rejected"


def test_missing_reply_expires_at_tick_and_the_goal_continues_within_its_lease():
    transport = ScriptedTransport()  # silence: nothing scripted
    broker, _seam = _broker(provider=Provider(_model_config(), transport, TOOL_SCHEMAS))
    broker.set_mission(mission_contract(), S(1.0))
    broker.set_goal(make_proposal("P1", "local", "fp-P1", 0, ("sel-0",), "explore", lease_s=30.0), S(1.2))
    request = make_request("req-1", 0, 1, ())
    broker.submit(request, RequestPacket(request=request, mission_instruction="m"), S(2.0))

    assert broker.tick(S(3.0)) == ()  # inside the deadline: nothing expires
    outcomes = broker.tick(S(6.5))
    assert [outcome.kind for outcome in outcomes] == ["request_expired"]
    assert "req-1 expired after 4.500s" in outcomes[0].reason
    assert "continuing within lease" in outcomes[0].reason
    record = broker.requests["req-1"]
    assert record.state == "expired"
    assert record.delay_not_zeroed_s == pytest.approx(4.5)
    # The active goal is still the same goal, still within its original lease.
    assert broker.active_goal_id == "g1"


def test_a_stale_observation_never_grounds_a_fresh_goal_and_its_age_is_recorded():
    payloads = _anomaly_episode_payloads()
    stale = [
        payload for payload in payloads
        if "stale_observation" in (payload.get("reason") or "")
    ]
    assert len(stale) == 1  # obs-2, delivered 7.8s late
    assert "age_s=9.800" in stale[0]["reason"]
    assert "observation_freshness" not in stale[0]["reason"]  # the bound value, not the key name
    assert stale[0]["disposition"] == "rejected"


# ---------------------------------------------------------------------------
# 3. Cancellation (§11, §15.2)
# ---------------------------------------------------------------------------


def test_cancel_with_the_wrong_revision_is_rejected_and_the_right_one_cancels_only_that_goal():
    broker, seam = _broker()
    broker.set_mission(mission_contract(), S(1.0))
    broker.set_goal(make_proposal("P1", "local", "fp-P1", 0, ("sel-0",), "explore"), S(1.2))
    broker.set_goal(make_proposal("P2", "local-2", "fp-P2", 1, ("sel-1",)), S(1.4))
    assert broker.active_goal_id == "g2"

    wrong = broker.cancel("g2", 99, "cancel-a", S(2.0))
    assert wrong.status.disposition is GoalDisposition.REJECTED
    assert "revision_mismatch" in wrong.status.reason
    assert seam.cancel_calls == []
    assert broker.active_goal_id == "g2"

    right = broker.cancel("g2", 2, "cancel-b", S(2.2))
    assert right.status.disposition is GoalDisposition.CANCELLED
    assert seam.cancel_calls == [("g2", 2, "cancel-b")]
    assert broker.active_goal_id is None  # only g2 was the active goal
    # g1's disposition is cancelled because g2 superseded it, and no cancel
    # call ever named it.
    assert len(seam.cancel_calls) == 1
    assert all(goal_id != "g1" for goal_id, _, _ in seam.cancel_calls)

    repeat = broker.cancel("g2", 2, "cancel-b", S(2.4))
    assert repeat.status.disposition is GoalDisposition.CANCELLED
    assert len(seam.cancel_calls) == 1  # the repeat never reached the seam


def test_cancel_of_an_unknown_goal_is_rejected_with_the_reason_named():
    broker, _seam = _broker()
    outcome = broker.cancel("g-none", 1, "cancel-z", S(1.0))
    assert outcome.status.disposition is GoalDisposition.REJECTED
    assert "unknown_goal" in outcome.status.reason


# ---------------------------------------------------------------------------
# 4. Leases (§15.1)
# ---------------------------------------------------------------------------


def test_lease_expiry_retires_a_goal_and_bounds_are_never_self_extended():
    broker, _seam = _broker()
    broker.set_mission(mission_contract(), S(1.0))
    broker.set_goal(make_proposal("P1", "local", "fp-P1", 0, ("sel-0",), "explore", lease_s=5.0), S(1.0))
    assert broker.goals["g1"].lease_s == 5.0

    for now_s in (2.0, 3.0, 4.0):
        broker.tick(S(now_s))
        assert broker.goals["g1"].lease_s == 5.0, "a lease does not extend itself"
        assert broker.active_goal_id == "g1"

    outcomes = broker.tick(S(6.5))
    assert [outcome.kind for outcome in outcomes] == ["goal_retired"]
    assert outcomes[0].reason == "lease_expired"
    assert broker.active_goal_id is None
    assert broker.goals["g1"].execution is ExecutionDisposition.STOPPED


# ---------------------------------------------------------------------------
# 5. Per-claim completion (§18.3)
# ---------------------------------------------------------------------------


def test_requested_counts_are_never_copied_into_observed_counts():
    now = S(10.0)
    claims = assemble_claims(
        requested_counts={"red-kettle": 3, "blue-box": 1},
        observed_counts={"red-kettle": 1},
        support_refs={"red-kettle": ("obs-1",)},
        now=now,
    )
    by_target = {claim.target: claim for claim in claims}
    kettle = by_target["red-kettle"]
    assert kettle.observed == 1 and kettle.kind is ClaimKind.OBSERVATION
    assert "requested_count=3_observed=1" in kettle.unmet_requirements
    unsupported = by_target["blue-box"]
    assert unsupported.observed == 0
    assert unsupported.kind is ClaimKind.INFERENCE
    assert "no supporting observation" in unsupported.unmet_requirements

    report = build_final_report(
        requested_counts={"red-kettle": 3},
        observed_counts={"red-kettle": 1},
        support_refs={"red-kettle": ("obs-1",)},
        termination_reason="bounds_exhausted",
        mission_revision=0,
        now=now,
    )
    assert report.claims[0].observed == 1
    assert report.unmet_requirements == ("requested_count=3_observed=1",)
    assert report.termination_reason == "bounds_exhausted"


# ---------------------------------------------------------------------------
# 6. The three executives under the same runner
# ---------------------------------------------------------------------------


class ScriptedWorld:
    """A permitted-evidence world: candidates appear only after movement, and
    a route can be blocked until a local step clears it."""

    def __init__(
        self,
        candidates_after: dict[int, tuple[str, ...]],
        frontiers: tuple[str, ...] = ("f1",),
        blocked_for_reports: dict[str, int] | None = None,
        budget_s: float = 60.0,
    ) -> None:
        self.candidates_after = candidates_after
        self.frontiers = frontiers
        # How many blocked reports a route survives before the local replanner
        # clears it. Modelling it in reports rather than in steps is what lets
        # a declared retry make progress.
        self.blocked_for_reports = blocked_for_reports or {}
        self.block_reports: dict[str, int] = {}
        self.budget_s = budget_s
        self.steps = 0
        self.consumed_s = 0.0
        self._observations = 0

    def discovered_candidates(self) -> tuple[str, ...]:
        found: tuple[str, ...] = ()
        for threshold, names in sorted(self.candidates_after.items()):
            if self.steps >= threshold:
                found = tuple(sorted(set(found) | set(names)))
        return found

    def known_frontiers(self) -> tuple[str, ...]:
        return self.frontiers

    def start_place(self) -> str:
        return "start"

    def is_blocked(self, target_ref: str) -> bool:
        remaining = self.blocked_for_reports.get(target_ref)
        if remaining is None:
            return False
        reports = self.block_reports.get(target_ref, 0)
        self.block_reports[target_ref] = reports + 1
        return reports < remaining

    def budget_remaining_s(self) -> float:
        return self.budget_s - self.consumed_s

    def step(self, action: str, target_ref: str | None) -> tuple[Observation, ...]:
        self.steps += 1
        self.consumed_s += 1.0
        self._observations += 1
        return (
            make_observation(
                f"obs-{self._observations}", self._observations,
                1_000_000_000 + self._observations * 1_000_000,
                1_000_500_000 + self._observations * 1_000_000,
                episode_id="executive-check",
            ),
        )

    def completion(self, action: str, target_ref: str | None) -> tuple[str, tuple[str, ...]]:
        return "achieved", (f"obs-{self._observations}",)


def _runner(broker: PilotBroker, world, start_s: float = 1.0):
    clock = {"ns": int(start_s * 1e9)}

    def now() -> ClockStamp:
        clock["ns"] += 100_000_000
        return ClockStamp(HOST, CLOCK, clock["ns"])

    runner = RecipeRunner(broker, world, now, sink=broker.sink)
    return runner


def test_b0_constructs_no_provider_and_completes_its_deterministic_recipe():
    executive = B0Conventional()
    assert not hasattr(executive, "provider")
    broker, seam = _broker(provider=None)
    broker.set_mission(mission_contract(), S(1.0))
    world = ScriptedWorld(candidates_after={1: ("c1",)}, frontiers=("f1", "f2"))
    result = _runner(broker, world).run(executive.build_recipe(world, mission_contract()))
    assert result.status == "completed"
    assert [step.action for step in result.steps] == ["explore", "inspect", "return"]
    assert broker.provider is None


class RecordingProvider(Provider):
    """Counts constructed instances, so 'B0 makes no provider' is measured."""

    constructions = 0

    def __init__(self, *args, **kwargs) -> None:
        type(self).constructions += 1
        super().__init__(*args, **kwargs)


def test_b1_makes_exactly_one_call_and_its_recipe_continues_past_the_first_waypoint():
    document = reply_document(())
    document["choices"][0]["message"]["content"] = json.dumps(
        {
            "mission_recipe": {
                "steps": [
                    {"action": "explore", "target_kind": "frontier", "target_ref": "next_unvisited",
                     "guard_kind": "always", "max_attempts": 1},
                    {"action": "inspect", "target_kind": "candidate", "target_ref": "next_uninspected",
                     "guard_kind": "candidate_present", "max_attempts": 3},
                    {"action": "return", "target_kind": "place", "target_ref": "start",
                     "max_attempts": 1},
                ],
                "bounds": {"max_steps": 6, "resource_ceiling": 8.0},
            }
        }
    )
    transport = ScriptedTransport()
    transport.schedule(ScriptedReply(delay_s=0.5, document=document))
    RecordingProvider.constructions = 0
    provider = RecordingProvider(_model_config(), transport, TOOL_SCHEMAS)
    assert RecordingProvider.constructions == 1

    broker, seam = _broker(provider=provider)
    broker.set_mission(mission_contract(), S(1.0))
    executive = B1OneShot(provider=provider)
    request = make_request("req-b1", 0, 0, ())
    executive.initial_request(
        broker, request, RequestPacket(request=request, mission_instruction="m"), S(2.0)
    )
    outcomes = broker.poll(S(3.0))
    parsed = next(outcome.parsed for outcome in outcomes if outcome.parsed is not None)
    recipe = executive.recipe_from_reply(parsed)
    assert recipe.source == "B1-one-shot"

    world = ScriptedWorld(candidates_after={1: ("c1",)}, blocked_for_reports={"c1": 1})
    result = _runner(broker, world, start_s=3.0).run(recipe)

    assert result.status == "completed"
    assert [step.action for step in result.steps] == ["explore", "inspect", "return"]
    inspect = next(step for step in result.steps if step.action == "inspect")
    assert inspect.attempts >= 2, "the declared retry after a blocked step did not happen"
    assert inspect.target_ref == "c1", "the target was not resolved from later local evidence"
    assert len(transport.sent_documents) == 1, "B1 made more than its one initial call"
    assert len(seam.admit_calls) == 3, "the recipe did not act past its first waypoint"

    with pytest.raises(OneShotBudgetSpent):
        executive.initial_request(
            broker, make_request("req-b1b", 1, 0, ()),
            RequestPacket(request=request, mission_instruction="m"), S(9.0),
        )


def test_b2_keeps_one_effective_request_and_applies_a_mid_flight_revision():
    transport = ScriptedTransport()
    transport.schedule(
        # The first request's reply is late and finds its request obsolete.
        ScriptedReply(delay_s=5.0, document=reply_document(
            (make_proposal("P-late", "req-1", "fp-late", 1, ("sel-0",)),))),
        # The replacement's reply is timely and carries a valid revision.
        ScriptedReply(delay_s=0.5, document=reply_document(
            (make_proposal("P-rev", "req-2", "fp-rev", 1, ("sel-0",)),))),
    )
    broker, seam = _broker(provider=Provider(_model_config(), transport, TOOL_SCHEMAS))
    broker.set_mission(mission_contract(), S(1.0))
    broker.set_goal(make_proposal("P1", "local", "fp-P1", 0, ("sel-0",), "explore"), S(1.2))
    observation = make_observation("obs-1", 1, 2_000_000_000, 2_050_000_000)
    broker.on_observation(observation, S(2.05))
    broker.register_selection(make_selection("sel-0", "obs-1"))

    engine = DecisionEngine(parameters(), MODEL_IDENTITY)
    executive = B2Continuous(provider=broker.provider, engine=engine)

    def packet_builder(decision):
        return RequestPacket(
            request=decision.request, mission_instruction="m",
            target_refs=decision.cited_observation_ids,
        )

    from embodied.pilot.decisions import SceneStatus

    executive.tick(broker, SceneStatus(signature=0.9, new_targets=("c1",)), packet_builder, S(3.0))
    assert broker.outstanding_request.request_id.startswith("req-")
    first = broker.outstanding_request.request_id
    outstanding_now = [
        record.request.request_id for record in broker.requests.values()
        if record.state == "outstanding"
    ]
    assert outstanding_now == [first], "more than one effective request is outstanding"

    # An urgent scene supersedes the first request: the replacement is the
    # second request and the first is not applied.
    executive.tick(broker, SceneStatus(signature=0.9, map_conflict=True), packet_builder, S(3.5))
    assert broker.requests[first].state == "obsolete"
    second = broker.outstanding_request.request_id
    assert second != first
    assert [
        record.request.request_id for record in broker.requests.values()
        if record.state == "outstanding"
    ] == [second]

    executive.tick(broker, SceneStatus(signature=0.9), packet_builder, S(4.2))
    assert broker.active_goal_id == "g2", "the admitted revision was not applied"
    assert broker.active_revision == 2
    assert seam.invalidations.get("g1") == seam.queued_samples
    # The superseded request's late reply was discarded without a second movement.
    executive.tick(broker, SceneStatus(signature=0.9), packet_builder, S(8.6))
    assert broker.active_goal_id == "g2"
    assert broker.active_revision == 2


# ---------------------------------------------------------------------------
# 7. Runner bounds exhaust into terminal reasons, never success (§20.2, §18.3)
# ---------------------------------------------------------------------------


def test_step_budget_exhaustion_is_a_terminal_reason_not_success():
    broker, _seam = _broker()
    broker.set_mission(mission_contract(), S(1.0))
    world = ScriptedWorld(candidates_after={0: ("c1",)}, frontiers=("f1",))
    recipe = MissionRecipe(
        steps=(
            RecipeStep("explore", TargetSelector("frontier", "next_unvisited")),
            RecipeStep("inspect", TargetSelector("candidate", "next_uninspected")),
            RecipeStep("return", TargetSelector("place", "start")),
        ),
        max_steps=1,
        resource_ceiling=10.0,
        source="bounds-check",
    )
    result = _runner(broker, world).run(recipe)
    assert result.status == "bounds_exhausted"
    assert "step budget 1" in result.reason
    assert result.status != "completed"


def test_resource_ceiling_exhaustion_is_a_terminal_reason_not_success():
    broker, _seam = _broker()
    broker.set_mission(mission_contract(), S(1.0))
    world = ScriptedWorld(candidates_after={0: ("c1",)}, frontiers=("f1",))
    recipe = MissionRecipe(
        steps=(
            RecipeStep("explore", TargetSelector("frontier", "next_unvisited"), step_cost=5.0),
            RecipeStep("inspect", TargetSelector("candidate", "next_uninspected"), step_cost=5.0),
        ),
        max_steps=10,
        resource_ceiling=5.0,
        source="bounds-check",
    )
    result = _runner(broker, world).run(recipe)
    assert result.status == "resources_exhausted"
    assert "resource ceiling 5.0" in result.reason


def test_an_unresolvable_target_exhausts_attempts_and_never_reports_success():
    broker, _seam = _broker()
    broker.set_mission(mission_contract(), S(1.0))
    world = ScriptedWorld(candidates_after={99: ("never",)}, frontiers=("f1",))
    recipe = MissionRecipe(
        steps=(
            RecipeStep(
                "inspect",
                TargetSelector("candidate", "next_uninspected"),
                guard=Guard("candidate_present"),
                max_attempts=3,
            ),
            RecipeStep("return", TargetSelector("place", "start")),
        ),
        max_steps=5,
        resource_ceiling=10.0,
        source="bounds-check",
    )
    result = _runner(broker, world).run(recipe)
    # The guard is false, so the step is skipped rather than faked; the recipe
    # then completes only its resolvable steps.
    assert result.steps[0].outcome == "guard_false"
    assert result.status in ("completed", "blocked", "bounds_exhausted")
    assert all(step.outcome != "achieved" for step in result.steps if step.target_ref == "never")


def test_a_recipe_with_bounds_is_required_to_have_them():
    with pytest.raises(ValueError):
        MissionRecipe(steps=(), max_steps=3, resource_ceiling=1.0, source="bad")
    with pytest.raises(ValueError):
        MissionRecipe(
            steps=(RecipeStep("teleport", TargetSelector("place", "start")),),
            max_steps=1,
            resource_ceiling=1.0,
            source="bad",
        )
