"""The grader accepts only claims that are both true and supported.

The slice's named grading behaviours, each pinned by one test here against
hand-written expected values:

* a supported object found/inspected/return claim passes;
* a found-claim for an absent object fails world correctness;
* an unrelated citation fails support even when the claim happens to be true;
* a count copied from the requested count fails;
* missing support annotation marks the score pending, not passed (exit 3).

Plus the truth-isolation invariant on the content side: the agent-readable
files carry no bench-private truth, and the fixture's committed score.json is
regenerated byte-for-byte, so the hand-checked numbers and the grader cannot
drift apart silently.
"""

import hashlib
import json
from pathlib import Path
import shutil

import embodied.bench.cli  # registers the bench command with the dispatcher
from embodied.cli import main
from embodied.bench.grader import ADJUDICATION_FILENAME, SCORE_FILENAME, grade

FIXTURE = Path(__file__).resolve().parents[1] / "fixtures" / "bench" / "hand-checkable-episode"

# Hand-computed from the fixture's truth-events.jsonl, final-report.json and
# adjudication.json. A change here is a review, not an update.
EXPECTED_PASSED = [True, True, True, False, False, False]
EXPECTED_WORLD = [True, True, True, False, True, False]
EXPECTED_SUPPORT = [
    "supported",
    "supported",
    "supported",
    "unsupported",
    "unsupported",
    "unsupported",
]


def _copy_fixture(tmp_path: Path) -> Path:
    destination = tmp_path / "episode"
    shutil.copytree(FIXTURE, destination)
    return destination


def _graded_copy(tmp_path: Path):
    episode = _copy_fixture(tmp_path)
    return episode, grade(episode)


def test_supported_claims_pass(tmp_path):
    _, score = _graded_copy(tmp_path)
    verdicts = score.claims
    assert [verdict.passed for verdict in verdicts[:3]] == [True, True, True]
    assert [verdict.world_correct for verdict in verdicts[:3]] == [True, True, True]
    assert [verdict.support for verdict in verdicts[:3]] == ["supported"] * 3
    assert all(verdict.reasons == () for verdict in verdicts[:3])


def test_a_found_claim_for_an_absent_object_fails(tmp_path):
    _, score = _graded_copy(tmp_path)
    verdict = score.claims[3]  # "found toolbox" — truth says absent
    assert verdict.predicate == "found"
    assert verdict.target == "toolbox"
    assert verdict.expected is False
    assert verdict.world_correct is False
    assert verdict.passed is False
    assert any("False" in reason for reason in verdict.reasons)
    assert score.report_correctness["false_asserted_confirmations"] == 1


def test_an_unrelated_citation_fails_even_though_the_claim_is_true(tmp_path):
    _, score = _graded_copy(tmp_path)
    verdict = score.claims[4]  # "found red_kettle" citing obs-3, a shelf frame
    assert verdict.world_correct is True  # a true guess stays true …
    assert verdict.support == "unsupported"  # … and still fails support
    assert verdict.passed is False
    assert any("unrelated" in reason for reason in verdict.reasons)


def test_a_count_above_the_recorded_evidence_fails(tmp_path):
    _, score = _graded_copy(tmp_path)
    verdict = score.claims[5]  # asserted 3, truth and evidence show 1
    assert verdict.predicate == "count"
    assert verdict.observed == 3
    assert verdict.expected == 1
    assert verdict.world_correct is False
    assert verdict.support == "unsupported"  # the annotation flags the copied count
    assert verdict.passed is False
    assert score.report_correctness["count_claims"] == 1
    assert score.report_correctness["incorrect_count_claims"] == 1


def test_the_totals_are_hand_computable(tmp_path):
    _, score = _graded_copy(tmp_path)
    assert [verdict.passed for verdict in score.claims] == EXPECTED_PASSED
    assert [verdict.world_correct for verdict in score.claims] == EXPECTED_WORLD
    assert [verdict.support for verdict in score.claims] == EXPECTED_SUPPORT

    correctness = score.report_correctness
    assert correctness["asserted_confirmations"] == 5
    assert correctness["false_asserted_confirmations"] == 1
    assert correctness["confirmation_precision"] == 0.8
    assert correctness["world_correct"] == 4
    assert correctness["world_incorrect"] == 2
    assert correctness["world_unverifiable"] == 0

    support = score.evidence_support
    assert support["supported"] == 3
    assert support["unsupported"] == 3
    assert support["unadjudicable"] == 0
    assert support["pending"] == 0
    assert support["adjudicable"] == 6
    assert support["support_precision"] == 0.5

    assert score.missed_present_targets == ()
    assert score.status == "complete"
    assert score.fully_passed is False
    assert score.mission["task_completion"] is False
    assert score.mission["safe_task_completion"] is False
    assert score.mission["physical_return_verified"] is True
    assert score.mission["interventions"] == 1


def test_the_grader_regenerates_the_committed_hand_checked_score(tmp_path):
    episode, _ = _graded_copy(tmp_path)
    assert (episode / SCORE_FILENAME).read_bytes() == (FIXTURE / SCORE_FILENAME).read_bytes()


def test_missing_adjudication_is_pending_not_a_pass(tmp_path):
    episode = _copy_fixture(tmp_path)
    (episode / ADJUDICATION_FILENAME).unlink()
    score = grade(episode)
    assert score.status == "pending"
    assert score.adjudication is None
    assert all(verdict.support == "pending" for verdict in score.claims)
    # World correctness is still computed; only support waits.
    assert [verdict.world_correct for verdict in score.claims] == EXPECTED_WORLD
    assert [verdict.passed for verdict in score.claims] == [
        None,
        None,
        None,
        False,
        None,
        False,
    ]
    assert score.evidence_support["adjudicable"] == 0
    assert score.evidence_support["support_precision"] is None

    output = tmp_path / "run"
    code = main(
        ["bench", "score", "--episode", str(episode), "--output", str(output)]
    )
    assert code == 3
    receipt = json.loads((output / "receipt.json").read_text(encoding="utf-8"))
    assert receipt["status"] == "pending"
    assert receipt["gate_status"] == "not_applicable"


def test_scoring_is_valid_data_even_when_the_episode_fails(tmp_path):
    committed = (FIXTURE / SCORE_FILENAME).read_bytes()
    output = tmp_path / "run"
    code = main(
        ["bench", "score", "--episode", str(FIXTURE), "--output", str(output)]
    )
    assert code == 0  # a completed losing episode is a valid result
    receipt = json.loads((output / "receipt.json").read_text(encoding="utf-8"))
    assert receipt["status"] == "complete"
    assert receipt["gate_status"] == "fail"  # the episode, not the command, failed
    # Re-scoring reproduces the committed score byte for byte.
    assert (FIXTURE / SCORE_FILENAME).read_bytes() == committed
    assert (output / SCORE_FILENAME).read_bytes() == committed


def test_a_claim_citing_an_observation_that_was_never_recorded_fails(tmp_path):
    episode = _copy_fixture(tmp_path)

    # The report lives in two synchronized places — the file and the stream
    # event — and the agent-side integrity checks bind both, so an edit keeps
    # them consistent and the manifest honest.
    report_path = episode / "final-report.json"
    report = json.loads(report_path.read_text(encoding="utf-8"))
    report["claims"][0]["support_refs"] = ["obs-99"]
    report_path.write_text(
        json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )

    events_path = episode / "agent-events.jsonl"
    rewritten = []
    for line in events_path.read_text(encoding="utf-8").splitlines():
        document = json.loads(line)
        if document["kind"] == "report":
            document["payload"]["claims"][0]["support_refs"] = ["obs-99"]
            line = json.dumps(document, sort_keys=True, separators=(",", ":"))
        rewritten.append(line)
    events_path.write_text("\n".join(rewritten) + "\n", encoding="utf-8")

    # The annotation follows the claim it describes, or the grader refuses it.
    annotation_path = episode / ADJUDICATION_FILENAME
    annotation = json.loads(annotation_path.read_text(encoding="utf-8"))
    annotation["entries"][0]["cited_evidence"] = ["obs-99"]
    annotation_path.write_text(
        json.dumps(annotation, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )

    manifest_path = episode / "manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    for member in ("agent-events.jsonl", "final-report.json"):
        manifest["artifacts"][member] = hashlib.sha256(
            (episode / member).read_bytes()
        ).hexdigest()
    manifest_path.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )

    score = grade(episode)
    verdict = score.claims[0]
    assert verdict.support == "supported"  # the annotation still says supported
    assert verdict.passed is False  # but the link resolves to nothing recorded
    assert any("obs-99" in reason for reason in verdict.reasons)


def test_an_explicit_adjudication_file_is_recorded_in_the_score(tmp_path):
    episode = _copy_fixture(tmp_path)
    annotation = tmp_path / "annotation.json"
    annotation.write_bytes((FIXTURE / ADJUDICATION_FILENAME).read_bytes())
    score = grade(episode, annotation)
    assert score.status == "complete"
    assert score.adjudication is not None
    assert score.adjudication["source"] == str(annotation)
    assert score.adjudication["version"] == "p02-adjudication-1"
    assert score.adjudication["rubric_revision"] == "hand-rubric-1"


def test_the_agent_readable_files_carry_no_bench_private_truth():
    banned = (
        b"world_state",
        b"world_counts",
        b"physical_outcome",
        b"return_verified",
        b'"takeover"',
    )
    for member in ("manifest.json", "agent-events.jsonl", "final-report.json"):
        data = (FIXTURE / member).read_bytes()
        for token in banned:
            assert token not in data, f"{member} leaks {token.decode()!r}"
    manifest = json.loads((FIXTURE / "manifest.json").read_text(encoding="utf-8"))
    projection = manifest["permitted_projection"]
    assert not any(
        name in member
        for member in projection
        for name in ("truth", "adjudication", "score")
    )
